### ISSUE TITLE
How to install dependence?

### ISSUE THREAD

**Issue by Mjunior1** [baguswiratmaadi/catnip#1]
How to install ALL dependence for example dmitry, theharvester, sslyze?

**Comment by ghost** [comment]
this tool i make for kali linux automation if you run in other OS Debian family you can install it 

with type apt install dmitry theharvester sslyze

if fail you can install it from source

or using pentest tools auto installer form this guy [Pentest Tools Auto Installer](https://github.com/Yukinoshita47/Pentest-Tools-Auto-Installer)
